name = "浙江省杭州市西湖区2024-2025学年初一下学期期末考科学试卷"
province = "浙江"
grade = "七年级"
year = 2024
subject = "科学"
page_id = "3370229393688403968"

[[stemlist]]
origin = "24-25七年级下·浙江杭州·期末"
stem = "1. 下列属于甲烷（CH4）分子结构模型的是（　　）A．B．C．D．"

[[stemlist]]
origin = "24-25七年级下·浙江杭州·期末"
stem = "2. 将新鲜荷叶的边缘剪出小孔，水能够通过小孔渗出，形成“天然花洒”，出现该现象的原因是荷叶中存在（　　）A．机械组织B．输导组织C．分生组织D．保护组织"

[[stemlist]]
origin = "24-25七年级下·浙江杭州·期末"
stem = "3. 下列化学用语中数字“2”表示分子个数的是（　　）A．2COB．Fe2+C．2CD．N2"

[[stemlist]]
origin = "24-25七年级下·浙江杭州·期末"
stem = "4. 今年，中国航天员在太空过端午，品尝特制“太空粽子”，天地连线送祝福。包装袋内的粽子从地球带至太空，其质量（　　）A．变大B．变小C．不变D．无法判断"

[[stemlist]]
origin = "24-25七年级下·浙江杭州·期末"
stem = "5. 西湖龙井茶区的土壤以白沙土为多，小科使用充分干燥后的白沙土进行如图所示实验，观察到白沙土变黑且质量变小，他想探究的是白沙土中含有（　　）A．空气B．水C．无机盐D．有机物"

[[stemlist]]
origin = "24-25七年级下·浙江杭州·期末"
stem = "6. 酸奶的发酵依靠乳酸菌，自制酸奶前需要将容器高温消毒，再将鲜牛奶煮沸，冷却后加入白砂糖和适量酸奶，最后放在30℃左右的环境中培养，如图所示。下列分析不正确的是（　　）A．高温消毒的目的是排除杂菌干扰B．乳酸菌属于细菌，没有成形的细胞核C．鲜牛奶中加入酸奶是为了加入乳酸菌D．在30℃左右培养，有利于乳酸菌通过孢子进行繁殖"

[[stemlist]]
origin = "24-25七年级下·浙江杭州·期末"
stem = "7. 进入青春期，人体在生长发育方面会发生某些变化，如图所示，以下分析正确的是（　　）A．进入青春期，大脑停止发育B．整个身体发育较快的时期只有青春期C．青春期开始出现第一性征D．青春期生殖器官迅速发育"

[[stemlist]]
origin = "24-25七年级下·浙江杭州·期末"
stem = "8. 如图所示的餐具为“夫人瓷”，又叫“西湖蓝筋囊富贵牡丹图餐具”。在餐具的制造中，以下过程发生了化学变化的是（　　）A．揉泥B．制坯C．干燥D．烧制"

[[stemlist]]
origin = "24-25七年级下·浙江杭州·期末"
stem = "9. 1803年，道尔顿提出以氢原子的质量为基准，其他原子与基准作比较得到其相对原子质量。若氢原子质量为n，氧原子质量为m，则氧原子的相对原子质量为（　　）A．B．C．D．"

[[stemlist]]
origin = "24-25七年级下·浙江杭州·期末"
stem = "10. 如图所示，金毛羚牛“头如马、角似鹿、蹄如牛、尾似驴”，现存数量少，其生殖发育过程与人相似，下列对金毛羚牛的生殖分析正确的是（　　）A．金毛羚牛的受精过程发生在卵巢内B．胚胎发育所需的营养物质均来自卵细胞C．胚胎发育的主要场所是子宫D．金毛羚牛的生殖方式为无性生殖"

[[stemlist]]
origin = "24-25七年级下·浙江杭州·期末"
stem = "11. 如图所示为冻干水果，其制作过程分为两个阶段：①冷冻阶段：将水果在低温下（如﹣30℃）快速冷冻，使内部水结冰；②干燥阶段：调节环境条件后，冰直接变成水蒸气，水果变得干燥酥脆。在①、②过程中，发生的物态变化分别是（　　）A．熔化；汽化B．凝固；升华C．液化；凝华D．升华；凝固"

[[stemlist]]
origin = "24-25七年级下·浙江杭州·期末"
stem = "12. 生物体结构与功能相适应是一个重要的科学观念，下列说法不正确的是（　　）A．根毛区细胞的表皮向外突起，有利于吸收土壤中的水和有机物B．有的细菌长有鞭毛，有利于细菌在液体中运动C．风媒花的花粉多而轻，有利于风力传播D．人体皮肤的表皮细胞排列紧密，主要起保护身体、防止细菌入侵的作用"

[[stemlist]]
origin = "24-25七年级下·浙江杭州·期末"
stem = "13. 某兴趣小组利用天平和量筒分别测量甲、乙两种液体的总质量（含容器质量）与体积，并依据所得数据绘制了总质量与液体体积关系图。下列说法正确的是（　　）A．随着体积的增大，液体甲的密度越来越大B．液体乙的密度是1.0×103千克/米3C．当液体质量相同时，液体甲、乙的体积之比为4∶5D．液体甲的密度小于液体乙的密度"

[[stemlist]]
origin = "24-25七年级下·浙江杭州·期末"
stem = "14. 小科设计了如图所示装置探究水的组成。下列说法不正确的是（　　）A．电池左端为正极，右端为负极B．水分子是由氢原子和氧原子构成C．甲气体可以使带火星的木条复燃D．该实验说明水是由氢气和氧气组成的"

[[stemlist]]
origin = "24-25七年级下·浙江杭州·期末"
stem = "15. 演绎是根据一类事物具有的一般性质、关系来推断这类事物中的个别事物所具有的性质、关系的方法。以下属于演绎的是（　　）A．燕子、麻雀、喜鹊等都有筑巢行为，所以鸟类有筑巢行为B．一个钠原子有11个质子和11个电子，因此它呈电中性C．晶体都有一定的熔点，冰是晶体，所以冰也有一定的熔点D．茎用导管运输水分，根能运输水分，因此根中也有导管"

[[stemlist]]
origin = "24-25七年级下·浙江杭州·期末"
stem = "16. 元素周期表将已知元素科学、有序地排列起来，便于我们研究它们的性质和用途。根据如图所示的部分元素周期表，回答以下问题：(1)表中N元素属于______元素（选填“金属”或“非金属”）。(2)写出②的元素符号______。(3)请写出镁元素和氧元素组成的化合物的化学式______。"

[[stemlist]]
origin = "24-25七年级下·浙江杭州·期末"
stem = "17. 在宏观、微观和符号之间建立联系有利于我们理解物质的构成。(1)物质的组成及构成关系如图所示，图中②表示的是______（选填“分子”或“原子”）。(2)从物质组成角度来看，碳酸钙（CaCO3）是由______种元素组成，其中钙元素的化合价为______。"

[[stemlist]]
origin = "24-25七年级下·浙江杭州·期末"
stem = "18. 如图甲所示为草履虫的结构图，现在低倍显微镜下观察草履虫。(1)观察前，在载玻片上的培养液中放几丝棉花纤维，其目的是______。(2)草履虫运动时通常______端在前（选填“A”或“B”），有利于摄食。(3)如图乙所示，草履虫是通过______方式进行无性生殖的。"

[[stemlist]]
origin = "24-25七年级下·浙江杭州·期末"
stem = "19. 漂流是一项热门的户外运动，借助特定工具（如汽艇、木筏等）在湍急的河流中顺流而下。某地想开发漂流项目，对该地进行了实地考察，并绘制了等高线地形图，如图所示，请回答下列问题。(1)①处地形的名称是______。(2)小科想登山，他选择D路线，而不选择C路线的理由是______。(3)若想规划漂流路线，应选择______路线（选填“A”或“B”）."

[[stemlist]]
origin = "24-25七年级下·浙江杭州·期末"
stem = "20. 宫保鸡丁是一道传统名菜，如图甲所示，制作时需要用到花生种子作为食材，如图丙所示。请回答下列问题：(1)花生种子在结构层次上属于________，它是由图乙中的________发育而来（选填字母）。(2)花生种子的营养物质主要储存在图丙中的________（选填数字）。"

[[stemlist]]
origin = "24-25七年级下·浙江杭州·期末"
stem = "21. 把湿餐布贴在刚从冰柜中拿出来的大虾表面，可以将大虾粘住并提起，如图所示。请解释这个现象：________，湿餐布粘住大虾所涉及的物态变化需要________（选填“吸热”或“放热”）。"

[[stemlist]]
origin = "24-25七年级下·浙江杭州·期末"
stem = "22. 小科利用如图甲所示装置进行探究水的沸腾特点实验，并绘制了温度和时间关系的图像，如图乙中a所示，请回答下列问题：(1)图甲中，用酒精灯加热时，应调整烧杯位置，使其置于酒精灯火焰的________（选填“焰心”“内焰”或“外焰”）处加热。(2)根据图乙可知，该实验中水的沸点为________℃。(3)若使用相同装置，仅将水的质量减少，其他条件不变，根据实验数据作出水温随时间变化的图像可能是图乙中的（　　）（选填字母）。A．aB．bC．cD．d"

[[stemlist]]
origin = "24-25七年级下·浙江杭州·期末"
stem = "23. 如图所示为治理沙漠时用到的“中国魔方”——草方格，它是用废弃的麦草一束束呈方格状铺在沙上，再用铁锹轧入沙中，留麦草的部分竖立在四边。为探究草方格对固沙效果的影响，某科学小组设计并进行如下实验：①取4组相同的沙盘，并轧入4组不同的草方格，分别记为A、B、C、D；②将4组沙盘放在风速为5m/s的环境中；③7天后测量并记录沙盘的沙土高度，如下表所示。组别草方格高度（cm）麦草轧入深度（cm）沙土初始高度（cm）7天后沙土高度（cm）A5520.017.2B51020.018.1C10520.017.6D15520.018.1根据题目信息，回答以下问题：(1)该实验中，通过______来判断草方格的固沙效果。(2)A、B两组实验探究的是______对固沙效果的影响。(3)比较A、C、D三组数据，可得出的结论是______。"

[[stemlist]]
origin = "24-25七年级下·浙江杭州·期末"
stem = "24. 小科为探究影响种子萌发的因素，设计了如下实验：(1)能否将1号瓶和4号瓶进行比较，判断并说明理由______。(2)2号瓶中的部分种子始终未能萌发，其原因可能是______。(3)实验改进后，小科想进一步探究种子萌发是否需要光照，请利用以上实验装置设计实验，简要写出实验方案：______。"

[[stemlist]]
origin = "24-25七年级下·浙江杭州·期末"
stem = "25. 图甲是“探究海波熔化过程中温度变化规律”的实验，每隔0.5min记录一次温度，并观察海波的状态，实验数据记录如下表：时间/min00.511.522.533.544.55温度/℃4042444648484848485052(1)第3分钟时，海波处于______状态；(2)实验过程中，海波宜选用较大颗粒还是较小颗粒，请判断并说明理由______；(3)根据实验数据，在如图乙所示的坐标纸上绘制出海波的温度随时间变化的图像______。"

[[stemlist]]
origin = "24-25七年级下·浙江杭州·期末"
stem = "26. 扩散是生活中常见的现象，那么，影响扩散快慢的因素有哪些呢？小科利用如图甲装置开展探究，向两个相同烧杯中，分别加入等体积的热水、冷水，用注射器和Y形管将红墨水缓慢注入水的底部，一段时间后，观察到如图乙所示现象。回答下列问题：(1)图甲中，采用注射器和Y形管进行实验的好处是______。(2)图乙中，装热水的烧杯是______（选填“A”或“B”）。(3)下列事例能用以上实验结论进行解释的是（　　）（选填字母）。A．春天气温回升，柳絮纷飞B．煮茶叶蛋比常温腌咸鸭蛋入味更快C．湿衣服摊开能干得更快"

[[stemlist]]
origin = "24-25七年级下·浙江杭州·期末"
stem = "27. 小科制作了如图所示的简易天平，O点是木杆的中点，在木杆的左右各挂一个相同的小桶，右侧小桶上标有刻度线，每一小格正好可以装10毫升水，已知水的密度为1.0×103kg/m3。小科使用该天平测量一块橡皮的质量，进行了如下操作：①移动燕尾夹，使木杆水平平衡；②将橡皮放入左侧小桶中；③再向右侧小桶加水，直至木杆再次水平平衡，读出小桶内水的体积为30毫升。请回答下列问题：(1)燕尾夹的功能与托盘天平中______的功能相同（填结构名称）。(2)根据实验计算得到橡皮质量为______克。(3)为了提高简易天平测量的精确度，以下改进措施可行的是（　　）（选填字母）。A．右侧小桶中换用密度比水大的液体B．右侧小桶中换用密度比水小的液体C．将右侧小桶的横截面积变大D．将右侧小桶的横截面积变小"

[[stemlist]]
origin = "24-25七年级下·浙江杭州·期末"
stem = "28. 近期，铁皮西红柿因独特外观在网络受到关注，如图甲所示。其果皮呈铁青色，且似有韧性“铁皮”质感。经研究发现：该品种可通过扦插繁殖，且植株生长存在顶端优势特征。(1)铁皮西红柿采用扦插繁殖，其优点是________。(2)若要促进侧枝生长从而提高铁皮西红柿的产量，可采取的方法是________。(3)铁皮西红柿常遭棉铃虫侵害，其幼虫有群集、啃食叶片的习性，而成虫善飞，活动范围较广，如图乙所示。为减少损失，防治棉铃虫的最佳时期是________阶段（选填“幼虫”或“成虫”）。"

[[stemlist]]
origin = "24-25七年级下·浙江杭州·期末"
stem = "29. 杨梅香气诱人，赋予其芳香味的物质之一是乙酸乙酯（化学式为C4H8O2），请根据化学式回答下列问题。(1)乙酸乙酯分子中碳、氢、氧三种原子个数的最简整数比为________。(2)乙酸乙酯的相对分子质量为________。(3)请列式计算乙酸乙酯中氧元素的质量分数是多少________？（精确到0.1%）"

[[stemlist]]
origin = "24-25七年级下·浙江杭州·期末"
stem = "30. 鸡蛋存放时间长会变质，小科查阅资料后了解到，鸡蛋的新鲜程度与密度之间的关系，如下表所示：密度（g/cm3）>1.051.02~1.05<1.02新鲜程度新鲜较新鲜变质于是，小科决定测量某个鸡蛋的密度，从而来判断该鸡蛋的新鲜程度。【测量步骤】①用调好的天平测得鸡蛋的质量，所用砝码和移动游码情况如图甲所示；②将鸡蛋放入装满水的溢水杯中，并用空量筒接住溢出来的水，如图乙所示；【数据分析】(1)这个鸡蛋的质量是________g。(2)请通过计算，结合资料判断鸡蛋的新鲜程度_______。(3)若将鸡蛋放入溢水杯中时，鸡蛋表面附着一些气泡，则会使测得的鸡蛋密度________（选填“偏大”“偏小”或“不变”）。"

[[stemlist]]
origin = "24-25七年级下·浙江杭州·期末"
stem = "31. 2020年，我国成功轧制出厚度为0.015mm的手撕钢，打破了全球手撕钢领域的最薄纪录。手撕钢主要采用轧制的方法将原本较厚的金属坯料通过一对旋转轧辊的间隙，使其变薄，如图甲所示，请回答下列问题。1.厚度对耐折叠次数的直接影响厚度0.05mm的手撕钢可耐受数千次折叠厚度0.02mm以下的手撕钢可耐受数万次折叠。(1)手撕钢能轧制成功，主要是利用了钢的（　　）（选填字母）。A．延展性B．导热性C．导电性D．可燃性(2)手撕钢是折叠屏手机底衬的重要材料，为了解手撕钢耐折叠次数与厚度的关系，小科询问人工智能，得到部分结果如图乙所示。①根据人工智能回答，推测手撕钢耐折叠次数与厚度的关系是________。②对于人工智能的回答，你的看法是(      )（选填字母）。A.人工智能回答一定是对的B.查阅可靠文献作为参考，判断回答的可靠性C.如有条件，可通过实验验证回答的可靠性"

[[stemlist]]
origin = "24-25七年级下·浙江杭州·期末"
stem = "32. 如图甲所示，是小科设计的“免浇水花盆”，它分为两个部分，上方是栽培盆，下方是储水盆，下雨时雨水能从栽培盆流向储水盆，天晴时吸水树脂能从储水盆吸水为土壤提供水分，请回答以下问题：(1)给栽培盆加装盆盖，减小了土壤表面与空气的接触面积，目的是________。(2)种植一段时间后，小科发现植株的茎秆软弱，向土壤中施加了氯化钾（KCl），主要是为了给植物补充________（选填“钾单质”或“钾元素”）。(3)植物的根对水分的吸收与细胞液及土壤溶液的浓度有关，如图乙所示，水分渗透的方向为①→②→③，由此判断①、②、③三处溶液浓度最大的是________。(4)小科发现在降水较少的季节，花盆收集雨水的功能欠佳，以下改进措施有利于增加储水盆内水量的是（　　）（选填字母）。A．B．C．"
