name = "浙江省义乌市宾王学校2024-2025学年八年级下学期5月校本作业科学试卷"
province = "浙江"
grade = "八年级"
year = 2024
subject = "科学"
page_id = "3370230068015046656"

[[stemlist]]
origin = "23-24八年级下·浙江金华·阶段练习"
stem = "1. 模型法是学习科学的重要方法，下列不属于模型的是（　　）A．光线B．电路图C．水分子D．氢元素"

[[stemlist]]
origin = "23-24八年级下·浙江杭州·阶段练习"
stem = "2. 如图是条形磁体的磁场分布图。下列说法正确的是（　　）A．磁感应线是为了研究方便引入的假想曲线B．a处的磁场强弱与b处的磁场强弱相同C．该条形磁体的左端为N极，右端为S极D．置于a点的小磁针静止时南极指向左侧"

[[stemlist]]
origin = "24-25八年级下·浙江金华·阶段练习"
stem = "3. 兴趣小组同学做了以下实验。为了证明土壤中含有无机盐的实验是（　　）A．B．C．D．"

[[stemlist]]
origin = "24-25七年级下·浙江绍兴·阶段练习"
stem = "4. 嫦娥五号返回器携带月球土壤样品成功返回地球，月球土壤中含有较丰富的氦—3，而在地球上，氦元素主要以氦—4的形式存在。如图是氦—3和氦—4的原子结构示意图，图中“”代表（　　）A．质子B．中子C．电子D．原子核"

[[stemlist]]
origin = "23-24八年级下·浙江金华·期末"
stem = "5. 规范的操作是实验成功的前提，下列实验操作规范的是（）A．检验气密性性B．高锰酸钾制取氧气C．铁丝在氧气中燃烧D．放置氧气"

[[stemlist]]
origin = "18-19八年级下·浙江绍兴·期中"
stem = "6. 我国未来的航母将采用自行研制的电磁弹射器。电磁弹射器的弹射车与飞机前轮连接，并处于强磁场中，当弹射车内的导体通以强电流时，舰载机受到强大的推力而快速起飞。电磁弹射器工作原理与下列设备或用电器工作原理一致的是（　　）A．B．C．D．"

[[stemlist]]
origin = "17-18八年级下·浙江·期中"
stem = "7. 在FeO、Fe2O3、Fe3O4三种化合物中，与等质量铁元素相结合的氧元素的质量比是（）A．2：3：6B．12：8：9C．6：9：8D．1：3：4"

[[stemlist]]
origin = "24-25八年级下·浙江金华·阶段练习"
stem = "8. 如图为大自然中的氧循环示意图，下列说法错误的是（　　）A．氧循环过程中发生的是化学变化B．物质燃烧说明氧气能支持燃烧，说明氧气具有可燃性C．食物腐烂发生的是缓慢氧化反应D．氧气能供给动植物呼吸，是一种重要的资源"

[[stemlist]]
origin = "2015八年级下·浙江杭州·竞赛"
stem = "9. 右图是某家庭电路，闭合开关，灯不亮。用测电笔接触c点氖管不发光，接触d点氖管发光。已知该电路有两处故障，则下列判断正确的是（）A．ac间断路、bd间断路B．eb间断路、cd间短路C．ac间断路、cd间短路D．ac间断路、eb间断路"

[[stemlist]]
origin = "23-24八年级下·浙江杭州·期末"
stem = "10. 下列概念符合如图所示a、b、c之间关系的是（　　）A．分生区、根尖、根B．支气管、气管、肺C．质子、中子、原子D．单质、化合物、纯净物"

[[stemlist]]
origin = "24-25七年级下·浙江杭州·期中"
stem = "11. 从原子结构模型建立的过程，我们可以发现建立模型往往需要有一个不断完善、不断修正的过程，下列关于几位科学家的原子结构模型的叙述不正确的是（　　）A．依据提出时间先后顺序，正确的排列是①②④③B．如图②模型波尔认为电子只能在原子内的一些特定的稳定轨道上绕核运动C．汤姆生认为图①模型中正电荷均匀分布在整个面包内，电子像葡萄干镶嵌其中D．卢瑟福在实验基础上提出带负电的电子绕带正电且体积很小的原子核运动的图④模型"

[[stemlist]]
origin = "23-24八年级下·浙江杭州·期中"
stem = "12. 下列各组物质中含有相同原子团的是（　　）A．和B．和C．和D．和"

[[stemlist]]
origin = "2021八年级下·浙江·专题练习"
stem = "13. 下列图像符合描述情况的是（）A．①中表示：用KMnO4制取氧气时，随着反应进行，MnO2质量发生的变化B．②中表示：a、b两试管中分别装有等质量等浓度的双氧水，并向a试管中放入催化剂后，随着反应的进行，氧气的生成情况C．③中表示：用KMnO4制取氧气时，随着反应的进行，试管中剩余的固体质量变化情况D．④中表示：用双氧水制取氧气时，生成的氧气质量的变化情况"

[[stemlist]]
origin = "23-24九年级上·浙江·开学考试"
stem = "14. 在一密闭容器中，有甲、乙、丙、丁四种物质，反应前各物质的质量关系如下图刻度纸所示（例如：丙的质量为5g，丁的质量为3g），充分反应后，在同一张刻度纸上再次记录各物质的质量变化：刻度线I向左移动16格；刻度线II向左移动8格；刻度线III向左移动8格。下列说法正确的是（　　）A．该反应是化合反应B．丙一定是催化剂C．反应后丁的质量为8gD．反应生成的乙和丁的质量比为1：1"

[[stemlist]]
origin = "2021九年级上·浙江台州·竞赛"
stem = "15. 已知在相同条件下，气体的体积比等于它们的分子数之比。如图所示，带有均匀刻度的容器（左室开口，右室密闭）内有一个理想活塞（无摩擦且密封性良好），开始在刻度l的位置。常温下用电火花点燃右室气体时，活塞被推向左边，当逐渐恢复到原来的温度时活塞又逐渐向右滑动，最终停留在容器的中央处（生成的水体积忽略不计），则原H2与O2的混合气体中，H2与O2的体积比可能是（　　）①8︰1；②l︰8；③7︰2；④2︰7；⑤4︰5。A．①②B．③⑤C．②③D．①④"

[[stemlist]]
origin = "23-24八年级下·浙江杭州·期中"
stem = "16. 下列物质：①食盐水②水银③冰水混合物④液态氮⑤澄清石灰水⑥五氧化二磷属于混合物的是__________属于单质的是__________。"

[[stemlist]]
origin = "24-25八年级下·浙江金华·阶段练习"
stem = "17. 化学用语可准确、简洁表达化学信息，请用化学用语填空。(1)碘蒸气___________。(2)构成食盐的微粒是___________。"

[[stemlist]]
origin = "24-25八年级下·浙江金华·阶段练习"
stem = "18. 多肉植物颇受大众喜爱，不仅成为了家庭种植的新宠，更以它特有的“小清新”气质征服了很多年轻人的心。(1)种植大多数多肉植物，需要配制特定的营养土。如果种植的土壤水分比例过大，将导致植物的根不能正常呼吸而腐烂，俗称“霉根”。多肉植物种植在___________（填“壤土类土壤”“砂土类土壤”或“黏土类土壤”）中最有可能出现该现象；(2)雨水充足的春季，在多肉植物的茎上会长出一些不定根（如图），这些根能够从空气中吸收___________（填“水分和氧气”或“有机物”），帮助植物正常生长。"

[[stemlist]]
origin = "24-25八年级下·浙江金华·阶段练习"
stem = "19. 如图所示是小科家安装的带有漏电保护器的空气开关、电能表、三孔插座等设备的部分家庭电路。(1)图中①②两处需接入空气开关和电能表，则①处应接___________；(2)图中电灯与插座的连接方式是___________；(3)用测电笔接触三孔插座各个孔中的金属片，氖管会发光是___________（填“a”“b”或“c”）。"

[[stemlist]]
origin = "24-25八年级下·浙江金华·阶段练习"
stem = "20. 小明同学收集了一些微粒的资料，请你和他一起根据表格数据回答下列问题。粒子名称质子数中子数电子数A141414B263024C141418D141814(1)表格中属于互为同位素原子的是___________。(2)根据表格信息写出微粒B的符号___________。(3)比较C与D两种微粒，其中质量较大的是___________。"

[[stemlist]]
origin = "21-22八年级下·浙江金华·期末"
stem = "21. 某同学用如图装置验证可燃物燃烧的条件（夹持仪器已略去）。实验材料白磷和红磷的着火点分别是40℃、240℃。他将一定量的白磷、红磷分别浸入80℃热水中，均未燃烧。（1）白磷、红磷均未燃烧，两者都缺少的燃烧条件是_______；（2）为了使白磷燃烧，可进行的操作是_______。"

[[stemlist]]
origin = "24-25八年级下·浙江金华·阶段练习"
stem = "22. 表示呼吸系统的组成示意图，图二为肺泡与毛细血管之间的气体交换示意图，图三为人的膈肌收缩和舒张时在胸腔内的位置示意图，回答下列有关问题。(1)图一中的②为___________，可以保证气流通畅，并温暖、湿润和清洁吸入的空气；(2)图二所示的肺泡内气体按照d方向出肺泡时，膈肌处于图三中的___________状态。"

[[stemlist]]
origin = "24-25八年级下·浙江金华·阶段练习"
stem = "23. 如图所示，学校综合实践小组用一段漆包线绕成线圈abdc，用小刀刮去两端的漆皮，一端全部刮去，另一端只刮去半周。把线圈放在用硬金属丝做成的支架mn上，并按图示连接电路。闭合开关后，用手轻推一下线圈，线圈就开始转动。若将电源的正、负极对调，则线圈的转动方向与原来___________（选填“相同”或“相反”） ；若在开关和电源之间串联一个电阻，线圈的转速将___________（选填“变快”、“不变”或“变慢”）。"

[[stemlist]]
origin = "24-25八年级下·浙江金华·阶段练习"
stem = "24. 在探究植物的各种生命现象实验中，需要对植物进行不同的处理。请据图分析：(1)在“研究植物呼吸作用”的实验中，需将新鲜菠菜密闭于塑料袋在暗处放置一个晚上，其中在暗处放置的目的是防止植物___________的干扰 。(2)如果将袋内的菠菜换成新鲜的植物种子，___________（填“需要”或“不需要”）暗处理。"

[[stemlist]]
origin = "2021八年级下·浙江·专题练习"
stem = "25. 为了研究“电磁铁磁性的强弱跟哪些因素有关”，小明利用电源、电流表、开关、滑动变阻器、导线、细铁钉、指针（带刻度）电磁铁（用漆包线制作的一个六抽头电磁铁，每20匝抽出一个接线端）等器材设计了如图甲、乙所示的装置进行探究。（1）图甲实验中小明是根据___________来判断磁性的强弱。（2）与图甲实验方案相比，图乙实验方案的优点是___________（3）小明利用图乙实验装置研究电磁铁磁性强弱与线圈匝数的关系。当线圈匝数从20匝换成100匝后，接下来应该进行的操作是：___________"

[[stemlist]]
origin = "24-25八年级下·浙江金华·阶段练习"
stem = "26. 根据如图所示装置，结合所学知识回答下列问题。(1)写出图中仪器①的名称___________。(2)实验室用B装置制取氧气，写出反应的化学方程式___________；D装置收集满氧气，接下来的操作是___________，并将集气瓶移出水面，正放在桌面上。(3)E装置中充满水时，也可作为氧气的收集装置，则氧气应从___________端通入（填“a”或“b”）。(4)氨气是一种有刺激性气味的气体，吸入人体会产生较大危害。其密度比空气小且极易溶于水，显碱性。实验室可用如下反应制取氨气：2NH4Cl（固体）+Ca（OH）2（固体）═2NH3↑+CaCl2+2H2O。小奕认为制取氨气时可用E装置来收集，其他同学认为不妥 ，应选择如图2装置中的甲和________组合收集和处理氨气。（选填序号）"

[[stemlist]]
origin = "24-25八年级下·浙江金华·阶段练习"
stem = "27. 反季节种植花卉、蔬菜、水果时，通常采用补光措施，不同种类的植物在不同生长阶段会补不同颜色的光。为探究不同颜色的光对植物光合作用的影响，研习小组开展了以下实验。资料：CO2缓冲液可维持装置内CO2含量稳定，氢氧化钠溶液可吸收CO2。①取3套完全相同的装置，编号为1、2、3.在A容器（不透光且密闭）内放入一盆长势良好、形态相近的天竺葵，烧杯内装入适量的某种液体，如图为其中一套装置。将三套装置均置于25℃的恒温环境中。②实验开始前缓缓打开活塞，待到U形管两侧液面相平时，关闭活塞。③分别给1、2、3号装置内的植物照射强度相同且适宜的红光、黄光、绿光。④8小时后，观察并记录实验数据和现象，如下表所示。装置光照颜色环境温度（℃）U形管液面高度差（mm/8h）U形管左右液面状况1红25240左高右低2黄2530左高右低2绿2510右低坐高(1)实验步骤①中，烧杯中的液体最合适的是 ___________ ；A．CO2缓冲液B．清水C．氢氧化钠溶液(2)实验中观察到装置1、2中U形管液面均为左高右低，产生此现象是由于天竺葵光合作用___________呼吸作用导致。（填“强于”“弱于”或“等于”）(3)据表分析，补充照射___________光对天竺葵的生长效果最好。"

[[stemlist]]
origin = "24-25八年级下·浙江金华·阶段练习"
stem = "28. 某化学兴趣小组对教材中“测定空气里氧气含量”的实验（见图I）进行了大胆改进，设计图（Ⅱ）（选用容积为45mL的试管作反应容器）实验方案进行，收到了良好的效果。请你对比分析下面图I、图Ⅱ实验，回答下列有关问题：(1)图I实验中可以推测氮气具有的性质是___________（写出2点）。(2)图Ⅱ实验的操作步骤如下：①点燃酒精灯。②撤去酒精灯，待试管冷却后松开弹簧夹。③将少量红磷平装入试管中，将20mL的注射器活塞置于10mL刻度处，并按图Ⅱ中所示的连接方式固定好，再用弹簧夹夹紧橡皮管。④读取注射器活塞的数据。你认为正确的实验操作顺序是___________（填序号）。(3)图Ⅱ实验中，注射器活塞将从10mL刻度处慢慢前移到约___________mL刻度处才停止。(4)细心的小明同学认为上述改进实验过程中当注射器活塞起始刻度不变时不用夹紧弹簧夹也能测定空气里氧气含量，请评价该同学说法是否合理并说明原因___________。"

[[stemlist]]
origin = "24-25八年级下·浙江金华·阶段练习"
stem = "29. 兴趣小组进行光合作用实验，选取生长状况相同的同种植物叶，分成4等份，分别在不同温度下暗处理1小时，接着在相同光照下放置1小时，测定每份叶中有机物质量的变化，制成图甲。回答下列问题。(1)实验中，叶在28℃时通过光合作用产生的有机物量是___________毫克。(2)若温度由28℃改为29℃，图乙中相应的a点在原位置___________方。(3)下列图示中能代表细胞中发生的情况与曲线中ab段相符的一项是___________ 。A．B．C．D．"

[[stemlist]]
origin = "24-25八年级下·浙江金华·阶段练习"
stem = "30. 阅读以下材料并回答问题。【材料一】氢元素的三种同位素原子分别是——氕（H，含1个质子）、氘（D，含1个质子和1个中子）、氚（T，含1个质子和2个中子）。【材料二】核废水中含有三种水，分别是水（H2O）、重水（D2O）和超重水（T2O）。【材料三】放射性元素的原子核放出射线的过程叫做衰变，超重水（T2O）中的氚（3H）元素会发生β﹣衰变，在这个过程中，氚原子核内一个中子会变成一个质子。(1)水（H2O）、重水（D2O） 和超重水（T2O）中共有___________种元素。(2)超重水（T2O）的相对分子质量是___________。(3)当核废水中的氚（3H）元素发生β﹣衰变时，会变成___________（填元素符号）。"

[[stemlist]]
origin = "24-25八年级下·浙江金华·阶段练习"
stem = "31. 随着国产电动汽车的兴起，锂资源的需求旺盛，“盐湖提锂”是获取锂资源的重要途径。扎布耶湖是中国第一大盐湖，碳酸锂（化学式为Li2CO3）储量185万吨。请回答：(1)碳酸锂中锂元素的化合价为___________。(2)碳酸锂中碳元素、氧元素和锂元素的质量比为___________。(3)若生产一辆电动汽车需要锂7千克，理论上扎布耶湖中的碳酸锂可供生产多少辆电动汽车。"

[[stemlist]]
origin = "23-24八年级下·浙江金华·期中"
stem = "32. 小王同学借助氧气传感器探究微粒的运动，用数据处理软件实时绘出氧气体积分数随时间变化的曲线。现收集一塑料瓶氧气进行以下三步实验：①敞口放置②双手贴在塑料瓶外壁上③将塑料瓶的瓶口朝下。三步实验中，测得氧气的体积分数随时间变化的曲线依次为图2中的MN段、NP段和PQ段。（1）能够说明氧分子不断运动的曲线是____（只有一个正确选项，填字母序号）。a．MN段b．NP段c．PQ段（2）MN段和NP段相比较，说明___________。（3）随着实验的进行，传感器测出氧气的体积分数约为_________时几乎不再变化。（4）现要制取4.8g氧气，试计算：至少需要加热多少克氯酸钾固体来制取？_________"

[[stemlist]]
origin = "24-25八年级下·浙江金华·阶段练习"
stem = "33. 小明乘电梯时，发现电梯超载会自动报警，于是真好钻研的他对电梯的电路图进行了研究，并设计了以下探究实验，如图甲所示，电源电压恒定不变，R0为定值电阻，用杯中水量调节压敏电阻受到力的大小，压敏电阻的电流与受到压力大小的关系如图乙所示：(1)图甲中，控制电路的开关S闭合时，电磁铁上端的磁极是___________极；(2)分析图乙I—F图像可知：压敏电阻受到的压力增大时，通过它的电流也增大，Rx的阻值_________（选填“变大”“变小”或“不变”）；当压力增大到一定程度时，触点K与________接触，电铃响，实现自动报警；(3)某电梯超载报警的Rx—F图像如图丙所示，空载时电梯厢对RX的压力F1等于电梯厢的重力，当压力F2=1×104N时，电梯报警，则此电梯限载几人？（每人质量约为50kg）"

[[stemlist]]
origin = "2021八年级下·浙江·专题练习"
stem = "34. 小华同学为了测定石灰石样品中碳酸钙的质量分数，取相等质量（）的五份样品分别与稀盐酸反应，其实验数据记录如下表所示（杂质既不溶于水也不与酸反应；不考虑二氧化碳在水中的溶解）。通过对数据的分析和比较，回答下列问题：盐酸的质量/g1020406080二氧化碳的质量g（1）的数值为______。（2）请在如图中画出在样品中加稀盐酸的质量与产生气体质量的关系图______。（3）稀盐酸的质量分数为______（精确到，下同）。（4）石灰石样品中碳酸钙的质量分数是多少______？"
